CREATE TABLE IF NOT EXISTS orders (
  id BIGINT unsigned NOT NULL AUTO_INCREMENT,
  customer VARCHAR(128) NOT NULL,
  item VARCHAR(128) NOT NULL,
  qty INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
